name: Auto Renew Tickhosting

on:
  schedule:
    - cron: '0 0 */4 * *'  # 每4天运行一次（96小时）,在UTC时间00:00运行
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  Auto_renew_tickhosting:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Pull latest changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull --rebase origin main
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Chrome and Playwright dependencies
      run: |
        # 安装 Chrome
        $chromePath = "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
        if (-not (Test-Path $chromePath)) {
            Invoke-WebRequest "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/win64/chrome-win64.zip" -OutFile "chrome.zip"
            Expand-Archive -Path "chrome.zip" -DestinationPath "$env:LOCALAPPDATA\Google\Chrome"
            Remove-Item "chrome.zip"
        }
        
        # 安装 Playwright 和相关依赖
        python -m pip install --upgrade pip
        pip install playwright requests python-dateutil
        python -m playwright install
        python -m playwright install-deps
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run auto renew script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PTERODACTYL_SESSION: ${{ secrets.PTERODACTYL_SESSION }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python auto_renew.py

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: debug-files
        path: |
          debug_*.png
          debug_*.html
          last_renew_data.txt

    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout main
        git add last_renew_data.txt
        git diff --cached --exit-code || git commit -m "Auto Update by Github Actions"
        git pull --rebase origin main || true
        git push origin main
